### ISSUE TITLE
Allow Node Selector and Tolerations to be customised

### ISSUE THREAD

**Issue by slacksach** [keycloak/keycloak-operator#408]
### Description

We run tainted nodes which require us to annotate our pods, having this facility in the operator would be very helpful

**Comment by andreaTP** [comment]
Hi @slacksach , sorry for the long delay, I do believe that this feature is being tackled in #491

**Comment by stianst** [comment]
Thanks (again) for reporting this issue. Keycloak 19 was the last version that included this legacy Operator, and with the release of Keycloak 20 the Operator reached EOL and this repository will be archived, please see our [blog post](https://www.keycloak.org/2022/03/releases.html) on this topic. If this issue is still valid for the [Realm Operator](https://github.com/keycloak/keycloak-realm-operator), please re-open it there. Thanks for your understanding. And be sure to check out our [new Operator](https://www.keycloak.org/guides#operator)!
