### ISSUE TITLE
Error: container has runAsNonRoot and image will run as root [securityContext]

### ISSUE THREAD

**Issue by Nold360** [keycloak/keycloak-operator#458]
### Description

Is there a possibility to apply a `securityContext` to the Keycloak deployment via the Operator?

My deployment failes with the Error message: `Error: container has runAsNonRoot and image will run as root`

### Motivation

Security. Containers should not run as root.

**Comment by andreaTP** [comment]
Hi @Nold360 !

Thanks for the issue and related PR, I understand the reasons to go in this direction but I would like to understand if you can achieve the same(or similar) result, using a custom Keycloak image.

More specifically you can set the environment variable `RELATED_IMAGE_KEYCLOAK` in the operator deployment to point to a custom image where you use the correct and more restricted permissions.

Or there are use-cases that cannot be covered with this approach?

**Comment by Nold360** [comment]
Well, you could use a custom image running as non-root but you would need the securityContext to specify fsGroup. And IDK if it would satisfy the PSP. Also there are more options available like readOnlyRootFilesysten/privilegeEscalation/...

Also... IMHO as a authentication tool Keycloak should be deployed as secure as possible.

**Comment by andreaTP** [comment]
Thanks for elaborating on the use-case!

I'll follow up on the PR review side.

**Comment by stianst** [comment]
Thanks (again) for reporting this issue. Keycloak 19 was the last version that included this legacy Operator, and with the release of Keycloak 20 the Operator reached EOL and this repository will be archived, please see our [blog post](https://www.keycloak.org/2022/03/releases.html) on this topic. If this issue is still valid for the [Realm Operator](https://github.com/keycloak/keycloak-realm-operator), please re-open it there. Thanks for your understanding. And be sure to check out our [new Operator](https://www.keycloak.org/guides#operator)!
