### ISSUE TITLE
Make KeycloakInstanceNotAvailable and KeycloakDatabaseNotAvailable alerts optional

### ISSUE THREAD

**Issue by tux-o-matic** [keycloak/keycloak-operator#470]
### Description

As [explained](https://github.com/keycloak/keycloak-operator/pull/114#issuecomment-571081372) by @davidffrench, these two alerts bundled with the Operator expect the kube state metrics are fed into the Prometheus instance monitoring Keycloak Pods.

### Motivation

These two bundled alerts are the only ones requiring kube state metrics.

### Details

It would be nice to make the creation of those two alerts conditional based on a boolean flag in the *Keycloak* CR, with default being `false`.

**Comment by andreaTP** [comment]
Hi @tux-o-matic ,

what you said seems completely legit to me, but I would default to the current behaviour (which is `true`) to preserve compatibility.

Would you be up to submit a PR with this improvement? 🙂

**Comment by tux-o-matic** [comment]
I wouldn't mind helping but Go isn't my strong suit and currently none of the rules are conditional so fixing this requires a new logic in the code.

**Comment by stianst** [comment]
Thanks (again) for reporting this issue. Keycloak 19 was the last version that included this legacy Operator, and with the release of Keycloak 20 the Operator reached EOL and this repository will be archived, please see our [blog post](https://www.keycloak.org/2022/03/releases.html) on this topic. If this issue is still valid for the [Realm Operator](https://github.com/keycloak/keycloak-realm-operator), please re-open it there. Thanks for your understanding. And be sure to check out our [new Operator](https://www.keycloak.org/guides#operator)!
