### ISSUE TITLE
Add support for adding Public/Private Key pairs to Realm

### ISSUE THREAD

**Issue by usamaahmadkhan** [keycloak/keycloak-operator#487]
### Description

For use cases where we want to add additional Keystores for applications.
![image](https://user-images.githubusercontent.com/18117459/153861877-5221f340-0cf6-493e-bc6f-eb8bbd12879f.png)

### Motivation

A new Keystore entry is required for an application so that the cert/keys are recognized by keycloak.

**Comment by andreaTP** [comment]
Hi @usamaahmadkhan thanks for your interest!
You should be able to provide an alternative Keystore by specifying [`X509_CA_BUNDLE`](https://github.com/keycloak/keycloak-containers/blob/3cb02a9f54e5cc005ec985228bd2871197f1d4ff/server/tools/x509.sh#L66) as an environment variable using the `experimental` settings (similar to [this](https://github.com/keycloak/keycloak-operator/blob/54f8f4344404747fa5d8fb751c7aace10e6437f5/deploy/examples/keycloak/keycloak-with-experimental-settings.yaml#L49) ) and mount the Keystore as a volume (similar to [this](https://github.com/keycloak/keycloak-operator/blob/54f8f4344404747fa5d8fb751c7aace10e6437f5/deploy/examples/keycloak/keycloak-with-experimental-settings.yaml#L52)).

Let me know if this fits your use-case!

**Comment by stianst** [comment]
Thanks (again) for reporting this issue. Keycloak 19 was the last version that included this legacy Operator, and with the release of Keycloak 20 the Operator reached EOL and this repository will be archived, please see our [blog post](https://www.keycloak.org/2022/03/releases.html) on this topic. If this issue is still valid for the [Realm Operator](https://github.com/keycloak/keycloak-realm-operator), please re-open it there. Thanks for your understanding. And be sure to check out our [new Operator](https://www.keycloak.org/guides#operator)!
