### ISSUE TITLE
Service Port 80 is not persistent

### ISSUE THREAD

**Issue by Craftoncu** [keycloak/keycloak-operator#507]
### Describe the bug

Good evening,

Since I want to do the TSL termination myself with Traefikv2, I need an HTTP mapping of Keycloak. 
I can create this and work with it until the operator overwrites this mapping and thus the port 8080 again. 
Is that intentional? Or is there another way to expose the HTTP port within the cluster?

### Version

17

### How to Reproduce?

1. Keycloak instance deployment
2. delete keycloak service
3. create own service as cluster ip with HTTP port mapping

**Comment by vmuzikar** [comment]
@Craftoncu Thank you for reporting this. Yes, this is intentional. The operator does not support HTTP, only HTTPS. 
However, we're currently developing a [new operator](https://github.com/keycloak/keycloak/tree/main/operator) where we will actually support HTTP mode. It will be released as part of [Keycloak 18](https://www.keycloak.org/2022/03/releases).
