### ISSUE TITLE
Improve `POSTGRES_EXTERNAL_ADDRESS` documentation

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak-operator#526]
### Description

Add an explicit note to the [Operator documentation](https://github.com/keycloak/keycloak-documentation/blob/main/server_installation/topics/operator/external-database.adoc) about using service hostname in the `POSTGRES_EXTERNAL_ADDRESS`  instead of IP in case users are creating a Service for their DB instance.

**Comment by stianst** [comment]
Thanks (again) for reporting this issue. Keycloak 19 was the last version that included this legacy Operator, and with the release of Keycloak 20 the Operator reached EOL and this repository will be archived, please see our [blog post](https://www.keycloak.org/2022/03/releases.html) on this topic. If this issue is still valid for the [Realm Operator](https://github.com/keycloak/keycloak-realm-operator), please re-open it there. Thanks for your understanding. And be sure to check out our [new Operator](https://www.keycloak.org/guides#operator)!
