### ISSUE TITLE
Add WebAuthn fields to the CRD

### ISSUE THREAD

**Issue by stustison** [keycloak/keycloak-operator#539]
### Description

The operator supports configuring the realm, but the KeycloakRealm resource is missing the WebAuthn fields from the [RealmRepresentation](https://www.keycloak.org/docs-api/17.0/rest-api/index.html#_realmrepresentation) model, so you can't configure Keycloak to use them.

**Comment by stianst** [comment]
Thanks (again) for reporting this issue. Keycloak 19 was the last version that included this legacy Operator, and with the release of Keycloak 20 the Operator reached EOL and this repository will be archived, please see our [blog post](https://www.keycloak.org/2022/03/releases.html) on this topic. If this issue is still valid for the [Realm Operator](https://github.com/keycloak/keycloak-realm-operator), please re-open it there. Thanks for your understanding. And be sure to check out our [new Operator](https://www.keycloak.org/guides#operator)!
