### ISSUE TITLE
PodDisruptionBudget being deprecated

### ISSUE THREAD

**Issue by CathalOConnorRH** [keycloak/keycloak-operator#543]
### Describe the bug

Openshift 4.9 shows the below in it's logs.

`W0916 09:39:32.937295       1 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget`

Raising issue for awareness and tracking

### Version

keycloak-operator(15.0.2) logs on openshift 4.8.10

**Comment by vmuzikar** [comment]
@CathalOConnorRH Thanks for the report. We're looking into it.

**Comment by stianst** [comment]
Thanks (again) for reporting this issue. Keycloak 19 was the last version that included this legacy Operator, and with the release of Keycloak 20 the Operator reached EOL and this repository will be archived, please see our [blog post](https://www.keycloak.org/2022/03/releases.html) on this topic. If this issue is still valid for the [Realm Operator](https://github.com/keycloak/keycloak-realm-operator), please re-open it there. Thanks for your understanding. And be sure to check out our [new Operator](https://www.keycloak.org/guides#operator)!
