### ISSUE TITLE
Custom User LDAP Filter 

### ISSUE THREAD

**Issue by iam-roger-io** [keycloak/keycloak-operator#546]
### Description

In the configuration of the ldap provider there is no option to configure the **"Custom User LDAP Filter"**

That field would be very helpful.

### Motivation

Many users use filter in this configuration, and without this option the configuration is incomplete.

**Comment by stianst** [comment]
Thanks (again) for reporting this issue. Keycloak 19 was the last version that included this legacy Operator, and with the release of Keycloak 20 the Operator reached EOL and this repository will be archived, please see our [blog post](https://www.keycloak.org/2022/03/releases.html) on this topic. If this issue is still valid for the [Realm Operator](https://github.com/keycloak/keycloak-realm-operator), please re-open it there. Thanks for your understanding. And be sure to check out our [new Operator](https://www.keycloak.org/guides#operator)!
