### ISSUE TITLE
add keycloak realm events expiration

### ISSUE THREAD

**Issue by zfrhv** [keycloak/keycloak-operator#553]
### Description

in the `KeycloakRealm` CRD i saw that the `eventsEnabled` exists just as with the api, but there is no `eventsExpiration`

could you please add `spec.realm.eventsExpiration` to the `KeycloakRealm` CRD ?

### Motivation

we can configure events but nothing to clean them, it can cause high disk usage

would be nice if we could do it from the CRD :)

**Comment by stianst** [comment]
Thanks (again) for reporting this issue. Keycloak 19 was the last version that included this legacy Operator, and with the release of Keycloak 20 the Operator reached EOL and this repository will be archived, please see our [blog post](https://www.keycloak.org/2022/03/releases.html) on this topic. If this issue is still valid for the [Realm Operator](https://github.com/keycloak/keycloak-realm-operator), please re-open it there. Thanks for your understanding. And be sure to check out our [new Operator](https://www.keycloak.org/guides#operator)!
