### ISSUE TITLE
keep default userFederationMappers

### ISSUE THREAD

**Issue by zfrhv** [keycloak/keycloak-operator#554]
### Description

when i want to append ldap mapper in `KeycloakRealm.spec.realm.userFederationMappers`, then the rest of the default mappeprs are being removed.

add an option to keep the default mappers, and just append/override the new specified mappers.

### Motivation

it saves a lot of work and configurations

**Comment by stianst** [comment]
Thanks (again) for reporting this issue. Keycloak 19 was the last version that included this legacy Operator, and with the release of Keycloak 20 the Operator reached EOL and this repository will be archived, please see our [blog post](https://www.keycloak.org/2022/03/releases.html) on this topic. If this issue is still valid for the [Realm Operator](https://github.com/keycloak/keycloak-realm-operator), please re-open it there. Thanks for your understanding. And be sure to check out our [new Operator](https://www.keycloak.org/guides#operator)!
