### ISSUE TITLE
If URL for the extension is not available at deployment time, the pods will crash

### ISSUE THREAD

**Issue by titansmc** [keycloak/keycloak-operator#561]
### Description

Pods won't start if all the extensions to install aren't available

### Motivation

silently fail to install the extensions and start the pods without them

**Comment by stianst** [comment]
Thanks (again) for reporting this issue. Keycloak 19 was the last version that included this legacy Operator, and with the release of Keycloak 20 the Operator reached EOL and this repository will be archived, please see our [blog post](https://www.keycloak.org/2022/03/releases.html) on this topic. If this issue is still valid for the [Realm Operator](https://github.com/keycloak/keycloak-realm-operator), please re-open it there. Thanks for your understanding. And be sure to check out our [new Operator](https://www.keycloak.org/guides#operator)!
