### ISSUE TITLE
Proper way of updating existing keycloak instance via related resource handled by operator

### ISSUE THREAD

**Issue by dejwsz** [keycloak/keycloak-operator#562]
### Describe the bug

It was started as a discussion - but maybe there is a bug behind this: https://github.com/keycloak/keycloak/discussions/12931,
I think operator should handle this but it looks like it is not?

### Version

18.0.0

### Expected behavior

To be able to change keycloak resource to force update to defined version - maybe by specifying image with proper tag?

### Actual behavior

I cannot see option for proper update other than manual updating of StatefulSet which is managed by operator as I understand - this looks dirty, kind a hack.

### How to Reproduce?

create 18.0.0 version of instance with keycloak legacy operator and try to update it to 18.0.2 with some clean approach which is not known to me

**Comment by dejwsz** [comment]
The same thing still in 19.0.1.
Also if you update "keycloakDeploymentSpec" for already existing keycloak resource it is not updated at all. You need to provide changes in StatefulSet manually.

**Comment by dejwsz** [comment]
What is interesting even if I modify envs in keycloakDeploymentSpec of keycloak spec (keycloak.org/v1alpha1) the operator does exactly noting - it does not update StetfulSet at all like nothing was changed, it needs to be done manually. Looks like this operator works only for first time while creating a cluster but later it is useless.

**Comment by stianst** [comment]
Thanks (again) for reporting this issue. Keycloak 19 was the last version that included this legacy Operator, and with the release of Keycloak 20 the Operator reached EOL and this repository will be archived, please see our [blog post](https://www.keycloak.org/2022/03/releases.html) on this topic. If this issue is still valid for the [Realm Operator](https://github.com/keycloak/keycloak-realm-operator), please re-open it there. Thanks for your understanding. And be sure to check out our [new Operator](https://www.keycloak.org/guides#operator)!
