### ISSUE TITLE
Prometheus pulling metric https keycloak

### ISSUE THREAD

**Issue by chary1112004** [keycloak/keycloak-operator#578]
### Description

Hi,

We are using keycloak operator to deploy keycloak 1.18 to EKS. We use prometheus pull metric from keycloak.
The internal service keycloak port 8443.

- For testing using curl inside pod, it requires to bypass certificate: curl -k https://keycloak-sandbox-service.keycloak-sandbox.svc.cluster.local:8443/auth/realms/master/metrics
- Prometheus: It could not pull metric from internal service with protocol https

Any clue in determining the solution how prometheus pull metric from keycloak would be very much appreciated.

Thank you!

**Comment by stianst** [comment]
Thanks (again) for reporting this issue. Keycloak 19 was the last version that included this legacy Operator, and with the release of Keycloak 20 the Operator reached EOL and this repository will be archived, please see our [blog post](https://www.keycloak.org/2022/03/releases.html) on this topic. If this issue is still valid for the [Realm Operator](https://github.com/keycloak/keycloak-realm-operator), please re-open it there. Thanks for your understanding. And be sure to check out our [new Operator](https://www.keycloak.org/guides#operator)!
