### ISSUE TITLE
Cannot reach Keycloak using the internalURL

### ISSUE THREAD

**Issue by droslean** [keycloak/keycloak-operator#586]
### Describe the bug

I am using the keycloak-operator in Kubernetes

My Keycloak object holds
```
    externalURL: https://keycloak.local
    internalURL: https://keycloak.keycloak-operator.svc:8443
```

But other pods can't reach Keycloak using the internalURL because they are getting the following error:

For example: `https://keycloak.keycloak-operator.svc:8443/auth/realms/master/protocol/openid-connect/token`
```
x509: certificate is not valid for any names, but wanted to match keycloak.keycloak-operator.svc
```

### Version

quay.io/keycloak/keycloak:19.0.2-legacy

### Expected behavior

No error

### How to Reproduce?

Just deploy keycloak-operator in Kubernetes

**Comment by stianst** [comment]
Thanks (again) for reporting this issue. Keycloak 19 was the last version that included this legacy Operator, and with the release of Keycloak 20 the Operator reached EOL and this repository will be archived, please see our [blog post](https://www.keycloak.org/2022/03/releases.html) on this topic. If this issue is still valid for the [Realm Operator](https://github.com/keycloak/keycloak-realm-operator), please re-open it there. Thanks for your understanding. And be sure to check out our [new Operator](https://www.keycloak.org/guides#operator)!
