### ISSUE TITLE
keycloakClient - serviceAccountClientRoles is not a recognized property?

### ISSUE THREAD

**Issue by norcron** [keycloak/keycloak-operator#590]
### Describe the bug

Hello! I'm trying to set an KeycloakClient so that it can use the client role of  `realm-management` and use the role `manage-users`.
So I'm using the `serviceAccountClientRoles` property inside `client` but the result is that it says its an unknown field.

Thanks in advance!

### Version

18.0.2

**Comment by stianst** [comment]
Thanks (again) for reporting this issue. Keycloak 19 was the last version that included this legacy Operator, and with the release of Keycloak 20 the Operator reached EOL and this repository will be archived, please see our [blog post](https://www.keycloak.org/2022/03/releases.html) on this topic. If this issue is still valid for the [Realm Operator](https://github.com/keycloak/keycloak-realm-operator), please re-open it there. Thanks for your understanding. And be sure to check out our [new Operator](https://www.keycloak.org/guides#operator)!
